spring:
  application:
    name: Unrest-API

application:
  security:
    jwk: ${application.security.path}key.jwk
  operations:
    disk:
      spin-up-all: ${application.operations.disk.socket}/update.htm?cmdSpinupAll=true&startState={state}&csrf_token={csrf}
      spin-down-all: ${application.operations.disk.socket}/update.htm?cmdSpindownAll=true&startState={state}&csrf_token={csrf}
      spin-up: ${application.operations.disk.socket}/update.htm?cmdSpinup={name}&startState={state}&csrf_token={csrf}
      spin-down: ${application.operations.disk.socket}/update.htm?cmdSpindown={name}&startState={state}&csrf_token={csrf}
    docker:
      version: "1.40"
      all-containers: ${application.operations.docker.socket}/v${application.operations.docker.version}/containers/json?all=true
      start-container: ${application.operations.docker.socket}/v${application.operations.docker.version}/containers/{id}/start
      stop-container: ${application.operations.docker.socket}/v${application.operations.docker.version}/containers/{id}/stop
      restart-container: ${application.operations.docker.socket}/v${application.operations.docker.version}/containers/{id}/restart
      kill-container: ${application.operations.docker.socket}/v${application.operations.docker.version}/containers/{id}/kill
      pause-container: ${application.operations.docker.socket}/v${application.operations.docker.version}/containers/{id}/pause
      unpause-container: ${application.operations.docker.socket}/v${application.operations.docker.version}/containers/{id}/unpause