spring:
  application:
    name: Unrest-API

application:
  state:
    disks: file:/app/config/state/disks.ini
    shares: file:/app/config/state/shares.ini
    var: file:/app/config/state/var.ini
  user:
    passwd: file:/app/config/passwd
    group: file:/app/config/group
    shadow: file:/app/config/shadow
  security:
    jwk: file:/app/config/security/key.jwk
  operations:
    disk:
      socket: /app/config/emhttpd.socket
      spin-up-all: /update.htm?cmdSpinupAll=true&startState={state}&csrf_token={csrf}
      spin-down-all: /update.htm?cmdSpindownAll=true&startState={state}&csrf_token={csrf}
      spin-up: /update.htm?cmdSpinup={name}&startState={state}&csrf_token={csrf}
      spin-down: /update.htm?cmdSpindown={name}&startState={state}&csrf_token={csrf}
    docker:
      socket: /app/config/docker.sock
      version: "1.40"
      all-containers: /v${application.operations.docker.version}/containers/json?all=true
      start-container: /v${application.operations.docker.version}/containers/{id}/start
      stop-container: /v${application.operations.docker.version}/containers/{id}/stop
      restart-container: /v${application.operations.docker.version}/containers/{id}/restart
      kill-container: /v${application.operations.docker.version}/containers/{id}/kill
      pause-container: /v${application.operations.docker.version}/containers/{id}/pause
      unpause-container: /v${application.operations.docker.version}/containers/{id}/unpause